version: '2'
services:
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
  dappy-node:
    container_name: dappy-node
    build: ./
    volumes:
      - ./:/var/www/app
    ports:
      - 3001:3001 # HTTP_PORT
      - 3002:3002 # HTTPS_PORT
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=3001
      - HTTPS_PORT=3002
      - CACHING=30
      - READ_ONLY=https://observer.testnet.rchain.coop
      - VALIDATOR=https://node0.testnet.rchain-dev.tk,https://node1.testnet.rchain-dev.tk,https://node4.testnet.rchain-dev.tk

    expose:
      - 3000
      - 80
    command: sh -c 'npm i && node --max-old-space-size=8192 src/index.js --ssl'
    depends_on:
      - redis
