services:
  pg:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dappy
    ports:
      - '5432:5432'
    volumes:
      - $PWD/.pgdata:/var/lib/postgresql/data
  adminer:
    image: amd64/adminer:4.8.1
    restart: always
    depends_on:
      - pg    
    ports:
      - 8082:8080      
