apiVersion: v1
data:
  dappynode.key: aafd56eaaaa....
  dappynode.crt: aacdf56aaac....
  rnode.key: aacdf56aaac....
  rnode.crt: aacdf56aaac....
  dhparams.pem: abbcdbcbab....
kind: Secret
metadata:
  name: sslsecret
type: Opaque
