apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources-configmap
data:
  dashboards.yml: |-
    apiVersion: 1

    providers:

    - name: 'Monitoring'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10 #how often Grafana will scan for changed dashboards
      options:
        path: /var/lib/grafana/dashboards  
  
  datasource.yml: |-
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090  
