apiVersion: v1
kind: Service
metadata:
  name: lb-dappy-node
spec:
  type: LoadBalancer
  loadBalancerIP: 195.154.71.146
  selector:
    app: dappy-node
  externalTrafficPolicy: Local
  ports:
    - port: 80
      name: http
      targetPort: 80
    - port: 443
      name: https
      targetPort: 443
