apiVersion: apps/v1
kind: Deployment
metadata:
  name: dappy-node
spec:
  template:
    spec:
      containers:
        - name: dappy-node
          env:
            - name: RCHAIN_NAMES_MASTER_REGISTRY_URI
              value: bwyeb7iiidaowwip6rowz4s645ytcqio34qu9g9qg66t5qjfcugqdo
            - name: RCHAIN_NAMES_CONTRACT_ID
              value: bwydappynamesystem
            - name: DAPPY_NETWORK
              value: gamma
            - name: RCHAIN_NETWORK
              value: testnet210604
            - name: VALIDATOR
              value: https://node2.testnet.rchain.coop
            - name: READ_ONLY
              value: https://observer.testnet.rchain.coop
            - name: READ_ONLY_CERTIFICATE_PATH
              value: ''
          volumeMounts:
          - name: rnode-tls
            mountPath: /ssl
            readOnly: true              
      volumes:
        - name: rnode-tls
          secret:
            secretName: rnode-tls              