apiVersion: apps/v1
kind: Deployment
metadata:
  name: dappy-jobs
spec:
  template:
    spec:
      containers:
        - name: get-contract-logs
          env:
            - name: MASTER_REGISTRY_URI
              value: bwyeb7iiidaowwip6rowz4s645ytcqio34qu9g9qg66t5qjfcugqdo
            - name: CONTRACTS
              value: "bwydappynamesystem"
            - name: READ_ONLY_CERTIFICATE_PATH
              value: /ssl/tls.crt
          volumeMounts:
          - name: rnode-tls 
            mountPath: '/ssl'
            readOnly: true
      volumes:
        - name: rnode-tls
          secret:
            secretName: rnode-tls              