apiVersion: apps/v1
kind: Deployment
metadata:
  name: dappy-jobs
spec:
  template:
    spec:
      containers:
        - name: get-contract-logs
          env:
            - name: DAPPY_NAMES_MASTER_REGISTRY_URI
              value: kgr7m8xo8od9ioiy1qoxxdgoiaesuwaaiixjccyf8aqebx7msibxnz
            - name: DAPPY_JOBS_LOGS_CONTRACTS
              value: kgrcontractns 
            - name: DAPPY_RCHAIN_READ_ONLY_CERTIFICATE_FILENAME
              value: /ssl/tls.crt
          volumeMounts:
          - name: rnode-tls 
            mountPath: '/ssl'
            readOnly: true
      volumes:
        - name: rnode-tls
          secret:
            secretName: rnode-tls              