apiVersion: apps/v1
kind: Deployment
metadata:
  name: dappy-jobs
spec:
  template:
    spec:
      containers:
        - name: get-contract-logs
          env:
            - name: RCHAIN_NAMES_MASTER_REGISTRY_URI
              value: iwusrr5g6zdywzh4mg5jydb5p3dh4edonz39jp33cb9eqi4zbehzs4
            - name: RCHAIN_NAMES_LOGS_CONTRACTS
              value: "iwudappynamesystem"
            - name: READ_ONLY_CERTIFICATE_PATH
              value: /ssl/tls.crt
          volumeMounts:
          - name: rnode-tls 
            mountPath: '/ssl'
            readOnly: true
      volumes:
        - name: rnode-tls
          secret:
            secretName: rnode-tls              