apiVersion: apps/v1
kind: Deployment
metadata:
  name: dappy-node
spec:
  template:
    spec:
      containers:
        - name: dappy-node
          env:
            - name: DAPPY_NAMES_MASTER_REGISTRY_URI
              value: kgr7m8xo8od9ioiy1qoxxdgoiaesuwaaiixjccyf8aqebx7msibxnz
            - name: DAPPY_NAMES_CONTRACT_ID
              value: kgrcontractns
            - name: DAPPY_JOBS_LOGS_CONTRACTS
              value: kgrcontractns
            - name: DAPPY_NETWORK
              value: gamma
            - name: DAPPY_RCHAIN_NETWORK
              value: testnet220418
            - name: DAPPY_RCHAIN_VALIDATOR
              value: https://node0.testnet.rchain.coop 
            - name: DAPPY_RCHAIN_READ_ONLY
              value: https://rnode
            - name: DAPPY_NODE_ENABLE_REQUEST_METRICS
              value: 'true'  
            - name: DAPPY_RCHAIN_READ_ONLY_CERTIFICATE_FILENAME
              value: '/ssl/tls.crt'
          volumeMounts:
          - name: rnode-tls
            mountPath: /ssl
            readOnly: true              
      volumes:
        - name: rnode-tls
          secret:
            secretName: rnode-tls              