apiVersion: apps/v1
kind: Deployment
metadata:
  name: dappy-node
spec:
  selector:
    matchLabels:
      app: dappy-node
  template:
    metadata:
      labels:
        app: dappy-node
    spec:
      containers:
        - image: fabcotech/dappy-node:latest
          name: dappy-node
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_DB
              value: '1'
            - name: CACHING
              value: '0'
            - name: HTTP_PORT
              value: '3001'
            - name: READ_ONLY
              value: http://aarnode:40403
            - name: VALIDATOR
              value: http://aarnode:40403
            - name: LAST_BLOCK_JOB_INTERVAL
              value: '40000'
            - name: RCHAIN_NAMES_CONTRACT_ID
              value: dappynamesystem
            - name: RCHAIN_NETWORK
              value: local
            - name: DAPPY_NETWORK
              value: local
            - name: RCHAIN_NAMES_MASTER_REGISTRY_URI
              valueFrom:
                configMapKeyRef:
                  name: master-uri
                  key: RCHAIN_NAMES_MASTER_REGISTRY_URI             
          ports:
            - containerPort: 3001
            - containerPort: 3002
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
      restartPolicy: Always