apiVersion: apps/v1
kind: Deployment
metadata:
  name: dappy-jobs
spec:
  template:
    spec:
      containers:
        - name: get-contract-logs
          env:
            - name: READ_ONLY
              value: https://observer-eu.services.mainnet.rchain.coop
            - name: RCHAIN_NAMES_LOGS_CONTRACTS
              value: ""
            - name: RCHAIN_NAMES_MASTER_REGISTRY_URI
              value: ""