apiVersion: apps/v1
kind: Deployment
metadata:
  name: dappy-jobs
spec:
  template:
    spec:
      containers:
        - name: get-contract-logs
          env:
            - name: DAPPY_RCHAIN_READ_ONLY
              value: https://observer-eu.services.mainnet.rchain.coop
            - name: DAPPY_JOBS_LOGS_CONTRACTS
              value: ""
            - name: DAPPY_NAMES_MASTER_REGISTRY_URI
              value: ""