apiVersion: apps/v1
kind: Deployment
metadata:
  name: dappy-jobs
spec:
  template:
    spec:
      containers:
        - name: get-contract-logs
          image: paulmusso/dappy-node:3.8
          env:
            - name: READ_ONLY
              value: https://observer-eu.services.mainnet.rchain.coop
            - name: CONTRACTS
              value: ""
            - name: MASTER_REGISTRY_URI
              value: ""