{
 "title": "Dappy-node",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request per minutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_ms_count[1m])) by (route, method, code)  * 60\n"
    }
   ]
  },
  {
   "title": "Success rate (2XX)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count{code=~\"^2..$\"}[1m])) /  sum(increase(http_request_duration_ms_count[1m]))"
    }
   ]
  },
  {
   "title": "95th Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_ms_bucket[1m])) by (le, service, route, method))"
    }
   ]
  },
  {
   "title": "Error rate (5XX)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count{code=~\"^5..$\"}[1m])) /  sum(increase(http_request_duration_ms_count[1m]))"
    }
   ]
  },
  {
   "title": "UpTime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - dappy_process_start_time_seconds"
    }
   ]
  }
 ]
}