apiVersion: v1
kind: ConfigMap
metadata:
  name: ipapp-nginx-config
data:
  index.html: |-
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Ip App</title>
    </head>
    <body>
      Ip App
    </body>
    </>
  nginx.conf: |-
    server {
        listen 8080;

        location / {
          root /www/data;
          index index.html;
        }
    }
