apiVersion: v1
kind: ConfigMap
metadata:
  name: ipapp-nginx-config
data:
  index.html: |-
    <!DOCTYPE html>
    <html lang="en">

    <head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Ip App</title>
    </head>

    <body>
      <p>Ip App</p>
      <video id="video"></video>
      <script>
        var ws = new WebSocket('wss://ipapp.dev/ws');
        ws.onmessage = msg => console.log(`Received from WS Server: ${msg.data}`);
        ws.onopen = () => {
          ws.send('foo');
        }

        var streaming   = false,
            video       = document.querySelector('#video'),
            cover       = document.querySelector('#cover'),
            canvas      = document.querySelector('#canvas'),
            photo       = document.querySelector('#photo'),
            width = 320,
            height = 0;

        navigator.getUserMedia(
          {
            video: true,
            audio: false
          },
          function (stream) {
            if (navigator.mozGetUserMedia) {
              video.mozSrcObject = stream;
            } else {
              video.srcObject = stream;
            }
            video.play();
          },
          function (err) {
            console.log("An error occured! " + err);
          }
        );
      </script>
    </body>
    </>   
  nginx.conf: |-
    server {
        listen 8080;

        location / {
          root /www/data;
          index index.html;
        }

        location /ws {
            proxy_pass http://localhost:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";            
            proxy_set_header Host $host;
        }
    }