apiVersion: apps/v1
kind: Deployment
metadata:
  name: dappy-jobs
spec:
  selector:
    matchLabels:
      app: dappy-jobs
  template:
    metadata:
      labels:
        app: dappy-jobs
    spec:
      containers:
        - image: fabcotech/dappy-node:latest
          name: get-contract-logs
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_URL
              value: redis://redis:6379/1
            - name: MASTER_REGISTRY_URI
              valueFrom:
                configMapKeyRef:
                  name: master-uri
                  key: RCHAIN_NAMES_MASTER_REGISTRY_URI   
            - name: READ_ONLY
              value: http://aarnode:40403
            - name: LOGS_INTERVAL
              value: '1000'
            - name: CONTRACTS
              value: dappynamesystem
            - name: START_JOB
              value: 'true'
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          command:
          - sh
          - '-c'
          - node src/jobs/get-contract-logs.js
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dappy-node
spec:
  selector:
    matchLabels:
      app: dappy-node
  template:
    metadata:
      labels:
        app: dappy-node
    spec:
      containers:
        - image: fabcotech/dappy-node:latest
          name: dappy-node
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_SERVICE_HOST
              value: redis
            - name: REDIS_DB
              value: '1'
            - name: CACHING
              value: '0'
            - name: NODEJS_SERVICE_PORT_3001
              value: '3001'
            - name: NODEJS_SERVICE_PORT_3002
              value: '3002'
            - name: READ_ONLY
              value: http://aarnode:40403
            - name: VALIDATOR
              value: http://aarnode:40403
            - name: LAST_BLOCK_JOB_INTERVAL
              value: '40000'
            - name: RCHAIN_NAMES_CONTRACT_ID
              value: dappynamesystem
            - name: RCHAIN_NETWORK
              value: local
            - name: DAPPY_NETWORK
              value: local
            - name: RCHAIN_NAMES_MASTER_REGISTRY_URI
              valueFrom:
                configMapKeyRef:
                  name: master-uri
                  key: RCHAIN_NAMES_MASTER_REGISTRY_URI             
          ports:
            - containerPort: 3001
            - containerPort: 3002
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: dappy-node
spec:
  type: NodePort
  selector:
    app: dappy-node
  ports:
    - name: '3001'
      port: 3001
      targetPort: 3001
    - name: '3002'
      port: 3002
      targetPort: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis
          name: redis
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: 6379
              hostPort: 6379
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - port: 6379
      name: redis
      targetPort: 6379

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dappy-https
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - hosts:
      - dappy.dev
      secretName: dappy-node-tls
  rules:
    - host: dappy.dev
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: dappy-node
              port:
                number: 3002