apiVersion: v1
kind: ConfigMap
metadata:
  name: rnode-nginx-config
data:
  nginx.conf: |-
    server {
      listen 443 ssl;

      ssl_certificate /ssl/tls.crt;
      ssl_certificate_key /ssl/tls.key;

      location / {
        rewrite /(.*) /$1 break;
        proxy_pass          http://localhost:40403;
        proxy_redirect      off;
        proxy_set_header    Host $host;
        proxy_connect_timeout 300s;
        proxy_read_timeout 300s;
      }
    }