apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aarnode
spec:
  selector:
    matchLabels:
      app: aarnode
  template:
    metadata:
      labels:
        app: aarnode
    spec:
      nodeSelector:
        rnode: "true"
      containers:
        - image: rchain/rnode:v0.12.2-rc1
          name: aarnode
          env:
            - name: BOOTSTRAP
              value: 'rnode://a383f7404d045e3e3fa4f5ebb200c92fb3fc8e18@node0.bm.testnet.rchain.coop?protocol=40400&discovery=40404'
            - name: RCHAIN_NETWORK
              value: 'testbm210724'
            - name: SHARD_NAME
              value: 'testbm'
            - name: CLUSTER_DOMAIN_NAME
              value: 'dappy.tech'
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - mountPath: '/ssl'
              name: sslsecret
              readOnly: true
          command: ['/opt/docker/bin/rnode']
          args:
            [
              'run',
              '--bootstrap',
              '$(BOOTSTRAP)',
              '--network-id',
              '$(RCHAIN_NETWORK)',
              '--shard-name',
              '$(SHARD_NAME)',
              --host,
              '$(HOSTNAME).$(RCHAIN_NETWORK).$(CLUSTER_DOMAIN_NAME)',
              '--protocol-port',
              '40400',
              '--discovery-port',
              '40404',
              '--api-port-grpc-external',
              '40401',
              '--api-port-http',
              '40403',
              '--finalization-rate',
              '1',
              '--max-number-of-parents',
              '1',
              '--fault-tolerance-threshold',
              '-1',
              '--synchrony-constraint-threshold',
              '0.99',
              '--fork-choice-stale-threshold',
              '60 minutes',
            ]
          ports:
            - containerPort: 40400
              hostPort: 40400
            - containerPort: 40401
              hostPort: 40401
            - containerPort: 40403
              hostPort: 40403
            - containerPort: 40404
              hostPort: 40404
          resources:
            requests:
              memory: 5Gi
              cpu: 1400m
      volumes:
        - name: sslsecret
          secret:
            secretName: sslsecret
      restartPolicy: Always
