apiVersion: apps/v1
kind: Deployment
metadata:
  name: dappy-node
spec:
  template:
    spec:
      containers:
        - name: dappy-node
          env:
            - name: RCHAIN_NAMES_MASTER_REGISTRY_URI
              valueFrom:
                configMapKeyRef:
                  name: master-uri
                  key: RCHAIN_NAMES_MASTER_REGISTRY_URI 
            - name: RCHAIN_NAMES_CONTRACT_ID
              valueFrom:
                configMapKeyRef:
                  name: master-uri
                  key: RCHAIN_NAMES_CONTRACT_ID