apiVersion: apps/v1
kind: Deployment
metadata:
  name: dappy-jobs
spec:
  template:
    spec:
      containers:
        - name: get-contract-logs
          env:
            - name: MASTER_REGISTRY_URI
              valueFrom:
                configMapKeyRef:
                  name: dappy-config 
                  key: RCHAIN_NAMES_MASTER_REGISTRY_URI