apiVersion: apps/v1
kind: Deployment
metadata:
  name: dappy-node
spec:
  template:
    spec:
      containers:
        - image: nginx:1.21.3
          name: nginx
          volumeMounts:
          - name: dappy-node-tls
            mountPath: /ssl
          - name: dappy-node-nginx-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: nginx.conf
          - name: dappy-node-nginx-config
            mountPath: /etc/nginx/snippets/sslparams.conf
            subPath: sslparams.conf
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
        - image: paulmusso/dappy-node:3.8
          name: dappy-node
          env:
            - name: CACHING
              value: '30'
            - name: CRON_JOBS_NAMES_MODULO
              value: '0'
            - name: DAPPY_NETWORK
              value: gamma
            - name: RCHAIN_NETWORK
              value: testbm210724
            - name: READ_ONLY
              value: https://rnode
            - name: VALIDATOR
              value: https://node0.bm.testnet.rchain.coop
          resources:
            limits:
              memory: 128Mi
              cpu: 200m
      volumes:
        - name: dappy-node-nginx-config
          configMap:
            name: dappy-node-nginx-config
        - name: dappy-node-tls
          secret:
            secretName: dappy-node-tls            