apiVersion: apps/v1
kind: Deployment
metadata:
  name: dappy-node
spec:
  template:
    spec:
      containers:
        - image: fabcotech/dappy-node
          name: dappy-node
          env:
            - name: DAPPY_NODE_CACHING
              value: '30'
            - name: DAPPY_RCHAIN_READ_ONLY
              value: https://rnode
            # - name: DAPPY_RCHAIN_READ_ONLY_CERTIFICATE_FILENAME
            #   value: /ssl/tls.crt
          resources:
            limits:
              memory: 128Mi
              cpu: 200m
      volumes:
        - name: dappy-node-nginx-config
          configMap:
            name: dappy-node-nginx-config
        - name: dappy-node-tls
          secret:
            secretName: dappy-node-tls            