apiVersion: apps/v1
kind: Deployment
metadata:
  name: dappy-jobs
spec:
  template:
    spec:
      containers:
        - name: get-contract-logs
          image: fabcotech/dappy-node
          env:
            - name: DAPPY_RCHAIN_READ_ONLY
              value: https://rnode
            - name: DAPPY_JOBS_LOGS_INTERVAL
              value: '120000'
          resources:
            limits:
              memory: '128Mi'
              cpu: '100m'              