bases:
- ../../../../base/dappy

resources:
- dappy-node-nginx-configmap.yaml
- dappy-node-service.yaml

patchesStrategicMerge:
- dappy-jobs-deployment.yaml
- dappy-node-deployment.yaml
- redis-service.yaml