bases:
- ../../../../base/dappy

resources:
- dappy-node-clusterip-service.yaml

patchesStrategicMerge:
- dappy-jobs-deployment.yaml
- dappy-node-deployment.yaml
- redis-service.yaml

images:
  - name: fabcotech/dappy-node
    newName: fabcotech/dappy-node
    newTag: '3.29.6'
