apiVersion: apps/v1
kind: Deployment
metadata:
  name: dappy-node
spec:
  selector:
    matchLabels:
      app: dappy-node
  template:
    metadata:
      labels:
        app: dappy-node
    spec:
      containers:
        - image: fabcotech/dappy-node:latest
          name: dappy-node
          imagePullPolicy: Always
          env:
            - name: DAPPY_RCHAIN_READ_ONLY
              value: http://rnode:40403
            - name: DAPPY_RCHAIN_VALIDATOR
              value: http://rnode:40403
            - name: DAPPY_RCHAIN_NETWORK
              value: local
            - name: DAPPY_NETWORK
              value: local       
            - name: DAPPY_NODE_CACHING
              value: '10'
            - name: DAPPY_NODE_REDIS_HOST
              value: $(REDIS_SERVICE_HOST)
            - name: DAPPY_NODE_REDIS_PORT
              value: $(REDIS_SERVICE_PORT)
          ports:
            - containerPort: 3001
            - containerPort: 3002
      restartPolicy: Always