apiVersion: v1
kind: ConfigMap
metadata:
  name: dappy-node-nginx-config
data:
  nginx.conf: |-
    limit_req_zone $binary_remote_addr zone=req_limit_per_ip:10m rate=2r/s;
    limit_conn_zone $binary_remote_addr zone=conn_limit_per_ip:10m;

    server {
      listen 80 default_server;
      location / {
        rewrite /(.*) /$1 break;

        proxy_pass http://localhost:3001;

        limit_req zone=req_limit_per_ip burst=10 nodelay;
        limit_conn conn_limit_per_ip 30;      
      }
    }

    server {
      listen 443 ssl http2;

      ssl_certificate /ssl/tls.crt;
      ssl_certificate_key /ssl/tls.key;

      include /etc/nginx/snippets/sslparams.conf;

      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Host $host;

      location / {
        rewrite /(.*) /$1 break;

        proxy_pass          http://localhost:3001;
        proxy_redirect      off;
        proxy_connect_timeout 300s;
        proxy_read_timeout 300s;

        limit_req zone=req_limit_per_ip burst=10 nodelay;
        limit_conn conn_limit_per_ip 30;
      }
    }
  sslparams.conf: |-
    # from https://www.cyberciti.biz/faq/configure-nginx-to-use-only-tls-1-2-and-1-3/
    # and https://blog.microjoe.org/2017/configuration-https-qualite-nginx.html

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers AES256+EECDH:AES256+EDH:!aNULL;
    ssl_ecdh_curve secp384r1;

    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;

    ssl_stapling on;
    ssl_stapling_verify on;

    resolver 8.8.8.8 8.8.4.4 valid=300s;
    resolver_timeout 5s;
    # Disable preloading HSTS for now.  You can use the commented out header line that includes
    # the "preload" directive if you understand the implications.
    #add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains";
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;

    ssl_dhparam /ssl/dhparams.pem;
